name: Checkmarx One Scan
on:
  pull_request:
  push:
    branches:
        - main
env:
 # platforms: Dockerfile
  scanTypes: iac-security,sast,sca
  threshold: iac-security-high=1=,iac-security-medium=1,iac-securitylow=1    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Sonar CLI Action 
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.externalIssuesReportPaths=./cx_result_sonar.json
    
         
     
